import { library } from '@fortawesome/fontawesome-svg-core';

// prettier-ignore
import { faGoogle } from '@fortawesome/free-brands-svg-icons';

// prettier-ignore
import {
  faArrowLeft,
  faArrowRight,
  faBars,
  faCheck,
  faClipboard,
  faClipboardCheck,
  faDownload,
  faEnvelope,
  faFolderImage,
  faPlus,
  faSignalStream,
  faSpinnerThird,
  faTrash,
  faWifi,
  faXmark,
  faYinYang,
} from '@fortawesome/pro-light-svg-icons';

// prettier-ignore
import {
  faBird,
  faBlockBrick,
  faBookHeart,
  faBookSparkles,
  faCakeSlice,
  faCalendarHeart,
  faCameraWeb,
  faCastle,
  faCat,
  faCauldron,
  faChampagneGlasses,
  faChurch,
  faCoffeePot,
  faCommentLines,
  faCrow,
  faDeer,
  faDragon,
  faEnvelopeOpenDollar,
  faEnvelopeOpenText,
  faFlaskRoundPotion,
  faFrog,
  faGem,
  faHatWizard,
  faHeartCrack,
  faImages,
  faImagesUser,
  faMessageHeart,
  faPegasus,
  faPeopleArrows,
  faPersonDressFairy,
  faPhotoFilm,
  faPlateUtensils,
  faRaccoon,
  faRestroom,
  faRingsWedding,
  faScrollOld,
  faSparkles,
  faSquirrel,
  faStarShooting,
  faTrees,
  faTurntable,
  faUsersViewfinder,
  faWandSparkles,
  faWhiskeyGlassIce,
  faWreathLaurel,
} from '@fortawesome/pro-duotone-svg-icons';

const buildLibrary = (): void => {
  // prettier-ignore
  library.add(
    // Brands
    faGoogle,
    // Lights
    faArrowLeft,
    faArrowRight,
    faBars,
    faCheck,
    faClipboard,
    faClipboardCheck,
    faDownload,
    faEnvelope,
    faFolderImage,
    faPlus,
    faSignalStream,
    faSpinnerThird,
    faTrash,
    faWifi,
    faXmark,
    faYinYang,
    // Duotone
    faBird,
    faBlockBrick,
    faBookHeart,
    faBookSparkles,
    faCakeSlice,
    faCalendarHeart,
    faCameraWeb,
    faCastle,
    faCat,
    faCauldron,
    faChampagneGlasses,
    faChurch,
    faCoffeePot,
    faCommentLines,
    faCrow,
    faDeer,
    faDragon,
    faEnvelopeOpenDollar,
    faEnvelopeOpenText,
    faFlaskRoundPotion,
    faFrog,
    faGem,
    faHatWizard,
    faHeartCrack,
    faImages,
    faImagesUser,
    faMessageHeart,
    faPegasus,
    faPegasus,
    faPeopleArrows,
    faPersonDressFairy,
    faPhotoFilm,
    faPlateUtensils,
    faRaccoon,
    faRestroom,
    faRingsWedding,
    faScrollOld,
    faSparkles,
    faSquirrel,
    faStarShooting,
    faTrees,
    faTurntable,
    faUsersViewfinder,
    faWandSparkles,
    faWhiskeyGlassIce,
    faWreathLaurel,
  );
};

export default { buildLibrary };
